CC=gcc
C-FLAG= -Wall -ansi

all:
	make exo1

exo1: exo1.c
	gcc -o exo1.o exo1.c -Wall -ansi

exo1.1: exo1.1.c
	gcc -o exo1.1.o exo1.1.c -Wall -ansi	

exo2: exo2.c
	gcc -o exo2.o exo2.c -Wall -ansi	

clean:
	rm *.o