all:
	make exo1

exo1: HelloWorld.c
	gcc -o HelloWorld.o HelloWorld.c -Wall -ansi

exo2: exo2.c
	gcc -o exo2.o exo2.c -Wall -ansi

exo3: exo3.c
	gcc -o exo3.o exo3.c -Wall -ansi

exo3.1: exo3.1.c
	gcc -o exo3.1.o exo3.1.c -Wall -ansi
exo4: exo4.c
	gcc -o exo4.o exo4.c -Wall -ansi
exo5: exo5.c
	gcc -o exo5.o exo5.c -Wall -ansi

clean:
	rm *.o